### ISSUE TITLE
Hello Packet

### ISSUE THREAD

**Issue by brownlegion** [sajeevany/COE865-Final#1]
Hello packets need to be sent to neighbouring hosts. The packets should include the IP of themselves, whatever resource they hold, and the IP and resources of its current neighbouring clients.

This can possibly be done as a Java class object. Then the data must be sent through the sockets to the clients, and they must be able to read that data. The data itself should be sent in bytes, rather than plain data values.

Packets include next hops, similar to routing table entries. Clients will advertise their neighbours and send that to other clients.

**Comment by sajeevany** [comment]
Added toString method for debugging purposes. Process stemmed from https://stackoverflow.com/questions/1066589/iterate-through-a-hashmap
